### ISSUE TITLE
SOURCE_TYPE_ROUTER was used from iphonedetect, this is a deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by Yulathh** [mudape/iphonedetect#108] opened 2024-03-16 05:00 UTC
I noticed the following in my HA log and they ask me to report it:

Logger: homeassistant.components.device_tracker.const
Source: helpers/deprecation.py:205
integration: Device tracker (documentation, issues)
First occurred: March 15, 2024 at 11:37:08 (1 occurrences)
Last logged: March 15, 2024 at 11:37:08

SOURCE_TYPE_ROUTER was used from iphonedetect, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please create a bug report at https://github.com/mudape/iphonedetect/issues

Is this being taken care of ? I've tried many device tracker with my iphones and they were all unreliable. Iphonedetetct is the only one which really works for me

**Comment by star114** [comment] 2024-03-17 10:41
duplicate of #101

**Closed** 2024-03-17 11:13 UTC
Labels: duplicate
